// Generated by assets/build-site.py — do not edit.
// Cache-first over a content-versioned cache: offline by default, and a deploy
// that changes any byte gets a new cache name, so updates can't go stale.
const VERSION = "c4bd6718e3de";
const CACHE = "japanese-" + VERSION;
const ASSETS = [
  "./",
  "assets/app.js",
  "assets/home.js",
  "assets/kana-drill.css",
  "assets/kana-drill.js",
  "assets/progress.js",
  "assets/quiz.js",
  "assets/style.css",
  "icon-180.png",
  "icon-192.png",
  "icon-512.png",
  "index.html",
  "lessons/0001-sumimasen-and-kudasai.html",
  "lessons/0002-numbers-and-prices.html",
  "lessons/0003-greetings.html",
  "lessons/0004-arimasu-ka-and-doko.html",
  "lessons/0005-understanding-directions.html",
  "lessons/0006-kana-diagnostic.html",
  "lessons/0007-the-fu-trap.html",
  "lessons/0008-what-survived.html",
  "manifest.webmanifest",
  "reference/kana-confusables.html",
  "reference/kana-trainer.html",
  "robots.txt"
];

self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (e) => {
  if (e.request.method !== "GET") return;
  e.respondWith(
    caches.match(e.request, { ignoreSearch: true }).then((hit) => {
      if (hit) {
        // Refresh in the background so the next launch is current.
        fetch(e.request).then((res) => {
          if (res && res.ok) caches.open(CACHE).then((c) => c.put(e.request, res));
        }).catch(() => {});
        return hit;
      }
      return fetch(e.request);
    })
  );
});
